### ISSUE TITLE
Issue running & deploying 

### ISSUE THREAD

**Issue by kelvindesman** [AnomalyInnovations/serverless-typescript-starter#1]
Hi, i've clone this repository through serverless install, i've follow the instruction 
npm install 
and tried run it but nothing work

```
internal/modules/cjs/loader.js:967
  throw err;
  ^

Error: Cannot find module '/Users/kelvindesman/apps/startup/knowid-backend/--max-old-space-size=2048'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```

**Comment by jayair** [comment]
That's weird. Can you share the versions of Node, npm, Serverless, etc.?

**Comment by cashmash** [comment]
Same issue here, with:

```
macOS Catalina Version 10.15.7
node v12.15.0 (npm v6.13.4)

sls --version                                                                                                                                    
Serverless: DOTENV: Loading environment variables from :
Framework Core: 2.11.1 (standalone)
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```

**Comment by jayair** [comment]
Instead of the `serverless install`, can you directly clone the repo?

**Comment by luxiconn** [comment]
I'm having the same issue directly cloning the repo

Windows 10 19042.685
node v12.16.2 (npm v6.14.4)

serverless --version
Framework Core: 1.78.1 (standalone)
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.33.4

**Comment by pcrodrigues0** [comment]
Any updates on this issue?

**Comment by jayair** [comment]
I'll need to try it again but I wasn't able to reproduce the issue.
